### ISSUE TITLE
Реализация силовых линий векторного поля

### ISSUE THREAD

**Issue by AntonTeoretik** [AntonTeoretik/Delta#13]
Реализовать функцию модуль `ForceLines` в файле ForceLines.hs, реализующий силовые линии векторного поля. Должен быть реализован тип данных `ForceLines` и функция `buildFromVecField :: Double -> (Point -> Vector) -> ForceLines`, где первый аргумент -- это радиус сферы где определено векторного поле.

**Comment by Teoretik-A** [comment]
Эта задача сделана.
